/*
 * XModel
 * Author: Bob Dunnagan
 * Copyright 2005. All rights reserved.
 */
package org.xmodel.xsd.check;

import java.util.List;
import org.xmodel.IModelObject;


/**
 * An interface for classes which perform validation at specific schema loci.
 */
public interface ICheck
{
  /**
   * Validate the specified document locus against the schema locus.
   * @param documentLocus The document locus.
   * @return Returns true if the document locus is valid.
   */
  public boolean validate( IModelObject documentLocus);
  
  /**
   * Returns the errors generated by this schema check.
   * @param errors The list where the errors will be added.
   */
  public void getErrors( List<SchemaError> errors);
  
  /**
   * Returns the schema locus validated by this instance.
   * @return Returns the schema locus validated by this instance.
   */
  public IModelObject getSchemaLocus();
}
